### ISSUE TITLE
How to confine leaves to one element?

### ISSUE THREAD

**Issue by oshihirii** [daftspunk/3d-falling-leaves#2]
Hello,

I cannot figure out how to confine leaves to one element.

I tried the following and the leaves fall through the whole `body` area.  

**HTML**

```
<body>
<script>

$(document).ready(function(){
$(".testing").octoberLeaves()
});

</script>

<div class="testing"></div>

</body>
```

**CSS**

```
.testing {
    background: #cccccc;
    width: 550px;
    height: 550px;
    margin:auto
}
```

**Comment by eaglei22** [comment]
In the 3d-falling-leaves script, I see line 98 has, " $('body').append(img)"  I believe this should be, "$(this.$el).append(img)"
